USE employees_db;

INSERT INTO department (name) VALUES ("Human Resources");
INSERT INTO department (name) VALUES ("Sales");
INSERT INTO department (name) VALUES ("Accounting");
INSERT INTO department (name) VALUES ("Quality Assurance");
INSERT INTO department (name) VALUES ("Customer Service");
INSERT INTO department (name) VALUES ("Management");

INSERT INTO roles (title, salary, department_id) VALUES ("Director", 100000.00, 1);
INSERT INTO roles (title, salary, department_id) VALUES ("Manager", 80000.00, 1);
INSERT INTO roles (title, salary, department_id) VALUES ("Coordinator", 60000.00, 1);
INSERT INTO roles (title, salary, department_id) VALUES ("Specialist", 50000.00, 1);
INSERT INTO roles (title, salary, department_id) VALUES ("Assistant", 40000.00, 1);
INSERT INTO roles (title, salary, department_id) VALUES ("Director", 100000.00, 2);
INSERT INTO roles (title, salary, department_id) VALUES ("Manager", 80000.00, 2);
INSERT INTO roles (title, salary, department_id) VALUES ("Coordinator", 60000.00, 2);
INSERT INTO roles (title, salary, department_id) VALUES ("Specialist", 50000.00, 2);
INSERT INTO roles (title, salary, department_id) VALUES ("Assistant", 40000.00, 2);
INSERT INTO roles (title, salary, department_id) VALUES ("Director", 100000.00, 3);
INSERT INTO roles (title, salary, department_id) VALUES ("Manager", 80000.00, 3);
INSERT INTO roles (title, salary, department_id) VALUES ("Coordinator", 60000.00, 3);
INSERT INTO roles (title, salary, department_id) VALUES ("Specialist", 50000.00, 3);
INSERT INTO roles (title, salary, department_id) VALUES ("Assistant", 40000.00, 3);
INSERT INTO roles (title, salary, department_id) VALUES ("Director", 100000.00, 4);
INSERT INTO roles (title, salary, department_id) VALUES ("Manager", 80000.00, 4);
INSERT INTO roles (title, salary, department_id) VALUES ("Coordinator", 60000.00, 4);
INSERT INTO roles (title, salary, department_id) VALUES ("Specialist", 50000.00, 4);
INSERT INTO roles (title, salary, department_id) VALUES ("Assistant", 40000.00, 4);
INSERT INTO roles (title, salary, department_id) VALUES ("Director", 100000.00, 5);
INSERT INTO roles (title, salary, department_id) VALUES ("Manager", 80000.00, 5);
INSERT INTO roles (title, salary, department_id) VALUES ("Coordinator", 60000.00, 5);
INSERT INTO roles (title, salary, department_id) VALUES ("Specialist", 50000.00, 5);
INSERT INTO roles (title, salary, department_id) VALUES ("Assistant", 40000.00, 5);
INSERT INTO roles (title, salary, department_id) VALUES ("Director", 100000.00, 6);
INSERT INTO roles (title, salary, department_id) VALUES ("Manager", 80000.00, 6);
INSERT INTO roles (title, salary, department_id) VALUES ("Coordinator", 60000.00, 6);
INSERT INTO roles (title, salary, department_id) VALUES ("Specialist", 50000.00, 6);
INSERT INTO roles (title, salary, department_id) VALUES ("Assistant", 40000.00, 6);

INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Jan", "Levinson", 26);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Michael", "Scott", 27, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Dwight", "Schrute", 30, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Pam", "Beesly", 25, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Jim", "Halpert", 7, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Stanley", "Hudson", 8, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Phyllis", "Lapin", 9, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Ryan", "Howard", 10, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Angela", "Martin", 11, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Oscar", "Martinez", 12, 9);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Kevin", "Malone", 12, 9);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Creed", "Bratton", 19, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Meredith", "Palmer", 17, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Kelly", "Kapur", 24, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ("Toby", "Flenderson", 1, 1);